name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - master

jobs:
  powershell:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - uses: actions/checkout@v4
      - run: Test-ModuleManifest ./Nvoip.psd1
      - run: Import-Module ./Nvoip.psm1 -Force
